### ISSUE TITLE
Texture looks streched on steep sides

### ISSUE THREAD

**Issue by DigitalMonkeyPa1** [Zylann/godot_heightmap_native_plugin#31]
Tri-Planar mapping can eliminate these, but performance may be disturbed.
[https://gamedevelopment.tutsplus.com/articles/use-tri-planar-texture-mapping-for-better-terrain--gamedev-13821](https://gamedevelopment.tutsplus.com/articles/use-tri-planar-texture-mapping-for-better-terrain--gamedev-13821)
This post explains how to use tri-planar mapping, but it is for jMonkey engine, but the shader code looks almost similar to godot's shader language.
Putting an option to enable or disable this one would be cool.

**Comment by Zylann** [comment]
I wish Godot had togglable #ifdef support in its shader pipeline, because that would be one of maaany options I wish the terrain shader could have... I cannot switch shader just for regions of the terrain, and I also can't have much options either at the moment, because of that.
So your only go is to modify the shader, which shouldn't be too difficult.

Also, using triplanar sounds like an expensive operation to add to a shader that some people already have difficulty to run (https://github.com/Zylann/godot_heightmap_native_plugin/issues/22). The current shader has to sample at least 8 textures at once + a few others + the ones Godot inserts internally. 8 fetches are used for splat textures. Triplanar multiplies those by 3, which becomes 24 fetches.... that's quite a lot, and further reduces the amount of users able to use it. (the article even explains performance is the first downfall).
That comes down to the technique being used of course, which I plan to migrate to texture arrays once Godot supports them, but I will still need 8 base fetches unfortunately...
Perhaps it could be reduced by using triplanar only on *some* of the splat textures though.

There is another alternative for cliffs that looks better, which is to use cliff meshes instead of leaving a stretched heightmap.

**Comment by DigitalMonkeyPa1** [comment]
That's ok, can you check this cool tool to make landscapes:
[http://www.dplate.de/tools/scapemaker](http://www.dplate.de/tools/scapemaker)
the features like height based water and foilage and clouds are nice.
By the way I mailed the developer to give code, it's now available on the website (he also warned me that it's over 12 years old, and unmaintained), just scrap it you may find something useful.
Hope you have some fun with it.

Before closing the issue let me try something with tri-planar thing for a few days, then I close this issue.

**Comment by Zylann** [comment]
I really intend to add a triplanar option to the first texture slot though, that should be ok for the time being.

ScapeMaker looks quite old indeed, but its generator might be of interest. Foliage is currently available in the `grass` branch, and trees are another subject to investigate in future updates but it might be just mesh-based with impostors.

**Comment by Zylann** [comment]
Without triplanar:
![image](https://user-images.githubusercontent.com/1311555/40571912-921fd802-60a1-11e8-93f1-624ab4d40e78.png)

With triplanar:
![image](https://user-images.githubusercontent.com/1311555/40571917-a1c1b618-60a1-11e8-9a86-980e41d4f02e.png)

I can have it optional on the 4th texture slot only.

**Comment by Zylann** [comment]
I just added an option to activate triplanar mapping on the last texture slot. It's not much, but at least allows to reduce stretching look on cliffs.

**Comment by DigitalMonkeyPa1** [comment]
Thank you so much.
But I am totally confused with the thing "Triplanar Mapping" - found in the docs ( 3D -> SpatialMaterial), is this "Triplanar Mapping" same as the one we have discussed.

**Comment by Zylann** [comment]
Yes, I took the same formulas to do it. My screenshots look like shit though, because I tested with a texture on which triplanar doesn't work nicely^^ but I'm sure it would work ok with a more organic natural texture.

**Comment by DigitalMonkeyPa1** [comment]
So, can I close this issue?

Can I contribute to this project, or do you want to make it on your own?

**Comment by Zylann** [comment]
You can close the issue if it's fixed for you.
You can also contribute to the project if you find things to fix or improve as well.

**Comment by DigitalMonkeyPa1** [comment]
Sorry, I was busy with a [grass_plugin_4_godot](https://github.com/marcosbitetti/grass_plugin_4_godot) by Marcos Augusto Bitetti, but was surprised that you made one.
Have a look at his video : [https://www.youtube.com/watch?v=-lxk_bLRBSg](https://www.youtube.com/watch?v=-lxk_bLRBSg)

It's made for Godot 2.x, I was trying to port it, at first I thought a few changes is enough, but its more complicated than I thought, a lot has changed from 2.x to 3.x.
But your grass implementation, especially UI is very compact, I liked it.

In that grass plugin, he uses MultiMeshInstance to hold mesh data, ie: loads grass mesh instead of pic, except default grass mesh, which is constructed in plugin code. Since every grass is a mesh(instance of multi-mesh) we can apply shaders like wind shader as material.

Can we apply shader materials to the grass in your implementation?

**Comment by Zylann** [comment]
Please open a different issue to ask about different topics.
