### ISSUE TITLE
Brief tutorial video?

### ISSUE THREAD

**Issue by brylie** [Zylann/godot_heightmap_native_plugin#43]
Hei,
I am having a bit of difficulty even figuring out how to start with this plugin. Would you consider publishing a brief tutorial video, showing how to create a simple terrain with this plugin and maybe a few modifiers?

BR,
Brylie

**Comment by Zylann** [comment]
I didn't write much docs at the moment because the plugin still is in beta stage, so if I made a video it would become obsolete after a month or two. But I have this in mind :)

For now, this is the only bit of doc I wrote, because I know that part isn't obvious at the moment: https://github.com/Zylann/godot_heightmap_native_plugin/blob/master/addons/zylann.hterrain/doc/main.md

**Comment by DigitalMonkeyPa1** [comment]
Thanks for the docs, I was wondering why the terrain gets disappear magically after closing & reopening the scene or project.
I was about to create an issue, but checking latest commit made sense.

**Comment by Zylann** [comment]
I'll close this since it is part of #18
